/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppOpportunitesRouteImport } from './routes/_app.opportunites'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCarteRouteImport } from './routes/_app.carte'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOpportunitesRoute = AppOpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteRoute = AppCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carte': typeof AppCarteRoute
  '/dashboard': typeof AppDashboardRoute
  '/opportunites': typeof AppOpportunitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carte': typeof AppCarteRoute
  '/dashboard': typeof AppDashboardRoute
  '/opportunites': typeof AppOpportunitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/carte': typeof AppCarteRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/opportunites': typeof AppOpportunitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carte' | '/dashboard' | '/opportunites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carte' | '/dashboard' | '/opportunites'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/carte'
    | '/_app/dashboard'
    | '/_app/opportunites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/opportunites': {
      id: '/_app/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof AppOpportunitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carte': {
      id: '/_app/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof AppCarteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCarteRoute: typeof AppCarteRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOpportunitesRoute: typeof AppOpportunitesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarteRoute: AppCarteRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOpportunitesRoute: AppOpportunitesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
